### ISSUE TITLE
Deploy static web pages

### ISSUE THREAD

**Issue by mscheinert** [immerse-project/nemo-simsar#13] opened 2020-10-08 13:56 UTC
## Description

The documentation is written as Markdown files in the doc/ folder. There is a script to create static html pages using mkdocs-material. Under a private github account I'm able to deploy it to github.io: (https://mscheinert.github.io/simsar/index.html). But under team "IMMERSE-project" I'm not able to use github pages because it is disbaled: It reads in the configuration:

> ### Upgrade or make this repository public to enable Pages
>
> GitHub Pages is designed to host your personal, organization, or project pages from a GitHub repository.
>
> Contact the owner of the repository to enable GitHub Pages.

And even if it is enabled, I'm not sure if it will merge with the existing webpage http://immerse-ocean.eu without any problems... Guess we will have to test it.

## Proposed solution

* [ ] Activate Github pages for the nemo-simsar project
* [ ] Rerun the deploy script and watch carefully if there is any interference with the project's site.

**Comment by lesommer** [comment] 2020-10-09 14:10
Well sometimes things work by pure magics. seems that the problem is sorted. We still need to check that all the links are working correctly though. I am therefore closing this issue.

**Closed by lesommer** 2020-10-09 14:10 UTC
